let valueHidden = false;

const elements1 = [
  // Nodes
  {
    id: "1",
    type: "default",
    data: { label: "1", value: "5", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "2",
    type: "default",
    data: { label: "2", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "3",
    type: "default",
    data: { label: "3", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "4",
    type: "default",
    data: { label: "4", value: "6", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "5",
    type: "default",
    data: { label: "5", value: "0", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  // Edges
  {
    id: "e1-2",
    source: "1",
    target: "2",
    data: { value: "2", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e1-3",
    source: "1",
    target: "3",
    data: { value: "3", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    data: { value: "6", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-5",
    source: "2",
    target: "5",
    data: { value: "5", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
];

const elements2 = [
  // Nodes
  {
    id: "1",
    type: "default",
    data: { label: "1", value: "5", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "2",
    type: "default",
    data: { label: "2", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "3",
    type: "default",
    data: { label: "3", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "4",
    type: "default",
    data: { label: "4", value: "6", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "5",
    type: "default",
    data: { label: "5", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "6",
    type: "default",
    data: { label: "6", value: "6", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "7",
    type: "default",
    data: { label: "7", value: "8", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "8",
    type: "default",
    data: { label: "8", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "9",
    type: "default",
    data: { label: "9", value: "0", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "10",
    type: "default",
    data: { label: "10", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  // Edges
  {
    id: "e1-2",
    source: "1",
    target: "2",
    data: { value: "2", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e1-3",
    source: "1",
    target: "3",
    data: { value: "3", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    data: { value: "6", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-5",
    source: "2",
    target: "5",
    data: { value: "5", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-6",
    source: "2",
    target: "6",
    data: { value: "4", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e3-7",
    source: "3",
    target: "7",
    data: { value: "8", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e7-8",
    source: "7",
    target: "8",
    data: { value: "2", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e7-9",
    source: "7",
    target: "9",
    data: { value: "6", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e9-10",
    source: "9",
    target: "10",
    data: { value: "2", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
];

const elements3 = [
  {
    id: "1",
    type: "default",
    data: { label: "1", value: "5", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
];

const elements4 = [
  // Nodes
  {
    id: "1",
    type: "default",
    data: { label: "1", value: "5", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "2",
    type: "default",
    data: { label: "2", value: "10", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "3",
    type: "default",
    data: { label: "3", value: "8", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "4",
    type: "default",
    data: { label: "4", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "5",
    type: "default",
    data: { label: "5", value: "9", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "6",
    type: "default",
    data: { label: "6", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "6",
    type: "default",
    data: { label: "6", value: "11", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "7",
    type: "default",
    data: { label: "7", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "8",
    type: "default",
    data: { label: "8", value: "0", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  // Edges
  {
    id: "e1-2",
    source: "1",
    target: "2",
    data: { value: "1", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-3",
    source: "2",
    target: "3",
    data: { value: "5", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    data: { value: "2", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e3-5",
    source: "3",
    target: "5",
    data: { value: "1", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e4-5",
    source: "4",
    target: "5",
    data: { value: "6", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e4-6",
    source: "4",
    target: "6",
    data: { value: "2", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e5-7",
    source: "5",
    target: "7",
    data: { value: "4", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e6-8",
    source: "6",
    target: "8",
    data: { value: "16", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
];

const elements5 = [
  // Nodes
  {
    id: "1",
    type: "default",
    data: { label: "1", value: "5", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "2",
    type: "default",
    data: { label: "2", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "3",
    type: "default",
    data: { label: "3", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "4",
    type: "default",
    data: { label: "4", value: "6", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "5",
    type: "default",
    data: { label: "5", value: "0", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "6",
    type: "default",
    data: { label: "6", value: "10", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "7",
    type: "default",
    data: { label: "5", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  // Edges
  {
    id: "e1-2",
    source: "1",
    target: "2",
    data: { value: "1", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e1-7",
    source: "1",
    target: "7",
    data: { value: "11", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-3",
    source: "2",
    target: "3",
    data: { value: "2", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    data: { value: "4", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e3-1",
    source: "3",
    target: "1",
    data: { value: "1", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e3-6",
    source: "3",
    target: "6",
    data: { value: "9", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e4-5",
    source: "4",
    target: "5",
    data: { value: "10", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
];

const elements6 = [
  // Nodes
  {
    id: "1",
    type: "default",
    data: { label: "1", value: "5", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "2",
    type: "default",
    data: { label: "2", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "3",
    type: "default",
    data: { label: "3", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "4",
    type: "default",
    data: { label: "4", value: "4", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "5",
    type: "default",
    data: { label: "5", value: "0", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "6",
    type: "default",
    data: { label: "6", value: "4", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "7",
    type: "default",
    data: { label: "7", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "8",
    type: "default",
    data: { label: "8", value: "6", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "9",
    type: "default",
    data: { label: "9", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "10",
    type: "default",
    data: { label: "10", value: "0", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "11",
    type: "default",
    data: { label: "11", value: "4", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "12",
    type: "default",
    data: { label: "12", value: "3", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "13",
    type: "default",
    data: { label: "13", value: "7", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "14",
    type: "default",
    data: { label: "14", value: "1", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "15",
    type: "default",
    data: { label: "15", value: "5", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "16",
    type: "default",
    data: { label: "16", value: "6", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "17",
    type: "default",
    data: { label: "17", value: "11", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "18",
    type: "default",
    data: { label: "18", value: "9", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "19",
    type: "default",
    data: { label: "19", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "20",
    type: "default",
    data: { label: "20", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  {
    id: "21",
    type: "default",
    data: { label: "21", value: "2", hidden: valueHidden },
    position: { x: 0, y: 0 },
  },
  // Edges
  {
    id: "e1-2",
    source: "1",
    target: "2",
    data: { value: "3", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e1-3",
    source: "1",
    target: "3",
    data: { value: "4", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-4",
    source: "2",
    target: "4",
    data: { value: "6", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e2-5",
    source: "2",
    target: "5",
    data: { value: "7", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e3-6",
    source: "3",
    target: "6",
    data: { value: "10", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e4-7",
    source: "4",
    target: "7",
    data: { value: "11", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e6-8",
    source: "6",
    target: "8",
    data: { value: "14", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e6-9",
    source: "6",
    target: "9",
    data: { value: "15", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e6-10",
    source: "6",
    target: "10",
    data: { value: "16", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e7-11",
    source: "7",
    target: "11",
    data: { value: "8", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e7-12",
    source: "7",
    target: "12",
    data: { value: "19", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e8-13",
    source: "8",
    target: "13",
    data: { value: "21", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e9-13",
    source: "9",
    target: "13",
    data: { value: "22", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e11-14",
    source: "11",
    target: "14",
    data: { value: "25", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e12-15",
    source: "12",
    target: "15",
    data: { value: "27", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e13-15",
    source: "13",
    target: "15",
    data: { value: "28", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e14-16",
    source: "14",
    target: "16",
    data: { value: "30", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e14-17",
    source: "14",
    target: "17",
    data: { value: "31", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e15-18",
    source: "15",
    target: "18",
    data: { value: "23", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e16-21",
    source: "16",
    target: "21",
    data: { value: "37", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e16-20",
    source: "16",
    target: "20",
    data: { value: "36", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e17-19",
    source: "17",
    target: "19",
    data: { value: "36", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e18-19",
    source: "18",
    target: "19",
    data: { value: "37", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
  {
    id: "e19-20",
    source: "19",
    target: "20",
    data: { value: "39", hidden: valueHidden },
    type: "straight",
    animated: false,
  },
];

export { elements1, elements2, elements3, elements4, elements5, elements6 };
